Isolate tests from local environment. (#278)
* Use py3-compatible syntax in test.

Since this test invokes `python`, you might get python 2 or 3. `print`
with parens should work on any somewhat recent python (2 or 3).

Fixes:
```
---- repo_version::tests::test_run_python_script stdout ----
thread 'repo_version::tests::test_run_python_script' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Error running version script (exit code 1; script: python version.py):\n\n  File \"/home/rcorre/version.py\", line 1\n    print \'1.2.3.4\'\n          ^\nSyntaxError: Missing parentheses in call to \'print\'. Did you mean print(\'1.2.3.4\')?\n" }', src/repo_version.rs:345:73
```

* Bypass global gitconfig.

Make it easier to run tests locally, without Docker. Setting
HOME/XDG_CONFIG_HOME bypasses global user config files, avoiding errors
like these (e.g. due to `init.defaultBranch=main`):

```
---- test_current_branch stdout ----
thread 'test_current_branch' panicked at 'assertion failed: `(left == right)`
  left: `"master"`,
 right: `"main"`', tests/git_test.rs:9:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_has_branch stdout ----
thread 'test_has_branch' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: should have master branch', tests/git_test.rs:18:5

---- test_does_branch_contain stdout ----
thread 'test_does_branch_contain' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: master should contain commit', tests/git_test.rs:37:5

---- test_checkout_branch_new_local_branch stdout ----
thread 'test_checkout_branch_new_local_branch' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Error running git (exit code 128, args: [\"checkout\", \"-B\", \"some-new-branch\", \"origin/master\"]):\nfatal:
\'origin/master\' is not a commit and a branch \'some-new-branch\' cannot be created from it\n" }', tests/git_test.rs:133:80

---- test_checkout_branch_already_checked_out stdout ----
thread 'test_checkout_branch_already_checked_out' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Error running git (exit code 128, args: [\"checkout\", \"-B\", \"master\", \"origin/master\"]):\nfatal: \'origin/master\' is not a commit and a branch \'master\' cannot be created from it\n" }', tests/git_test.rs:166:71

---- test_checkout_branch_already_exists stdout ----
thread 'test_checkout_branch_already_exists' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Error running git (exit code 128, args: [\"checkout\", \"-B\", \"the-branch\", \"origin/master\"]):\nfatal: \'origin/master\' is not a commit and a branch \'the-branch\' cannot be created from it\n" }', tests/git_test.rs:186:75

---- test_find_base_commit stdout ----
thread 'test_find_base_commit' panicked at 'Failed running git: `["checkout", "-b", "horses", "master"]`: ErrorMessage { msg: "Error running git (exit code 128, args: [\"-c\", \"user.name=Test User\", \"-c\", \"user.email=testy@octobot.com\", \"checkout\", \"-b\", \"horses\", \"master\"]):\nfatal: \'master\' is not a commit and a branch \'horses\' cannot be created from it\n" }', tests/git_helper/temp_git.rs:64:34
```