Update to rust 1.84. (#392)
This is the latest stable rust toolchain.
I had to run `cargo update` as some of the older
deps did not support latest rust.

I noticed a dependabot PR failed regarding a rust version mismatch:
https://github.com/tanium/octobot/pull/391

I'm not sure this will fix it, but it seems like a good step anyways.

---

I also changed the github action to explicity use ubuntu 22 instead of `latest`.
`latest` recently changed to ubuntu 24:

https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/

This fixes the following test failure

```
---- repo_version::tests::test_run_python_script stdout ----
thread 'repo_version::tests::test_run_python_script' panicked at ops/src/repo_version.rs:392:55:
called `Result::unwrap()` on an `Err` value: Error running version script (exit code 1; script: python version.py):

Access error: uid 1001, last mount name:/firejail/firejail.ro.file dir:/run/firejail/firejail.ro.file type:tmpfs - invalid noexec mount

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This may be related to sanbox changes in ubuntu 24:

- https://github.com/bazelbuild/bazel/issues/24081
- https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces

--- 

Run cargo clippy --fix to fix a bunch of new warnings, and manually fix the rest.