Try ubu22.04.
See if this fixes:

```
---- repo_version::tests::test_run_python_script stdout ----
thread 'repo_version::tests::test_run_python_script' panicked at ops/src/repo_version.rs:392:55:
called `Result::unwrap()` on an `Err` value: Error running version script (exit code 1; script: python version.py):

Access error: uid 1001, last mount name:/firejail/firejail.ro.file dir:/run/firejail/firejail.ro.file type:tmpfs - invalid noexec mount

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I know ubuntu 24 made some changes around sandboxing. It's possible that latest changed to 24 recently and broke this test.

https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/

> The ubuntu-latest label will migrate to Ubuntu 24 over the course of the next month, beginning September 23rd and finishing on October 30th

- https://github.com/bazelbuild/bazel/issues/24081
- https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces